### ISSUE TITLE
Parse error in convert_eprime.py

### ISSUE THREAD

**Issue by Setsu-BHMT** [tsalo/convert-eprime#1]
Hi!

Wanted to let you know of a corner case in your parsing script. Here's the pdb output:

> /convert_eprime.py(23)<module>()
> -> """
> (Pdb) c
> Traceback (most recent call last):
>   File "/usr/lib64/python2.6/pdb.py", line 1296, in main
>     pdb._runscript(mainpyfile)
>   File "/usr/lib64/python2.6/pdb.py", line 1215, in _runscript
>     self.run(statement)
>   File "/usr/lib64/python2.6/bdb.py", line 372, in run
>     exec cmd in globals, locals
>   File "<string>", line 1, in <module>
>   File "convert_eprime.py", line 395, in <module>
>     function(*sys.argv[2:])
>   File "convert_eprime.py", line 122, in text_to_csv
>     split_header_idx = one_row[j_col].index(": ")
> ValueError: substring not found
> Uncaught exception. Entering post mortem debugging
> Running 'cont' or 'step' will restart the program
> /convert_eprime.py(122)text_to_csv()
> -> split_header_idx = one_row[j_col].index(": ")
> (Pdb) l
> 117  
> 118         for i_row in range(n_rows):
> 119             one_row = filtered_data[start_index[i_row]+1:end_index[i_row]]
> 120             data_by_rows.append(one_row)
> 121             for j_col in range(len(one_row)):
> 122  ->             split_header_idx = one_row[j_col].index(": ")
> 123                 all_headers.append(one_row[j_col][:split_header_idx])
> 124  
> 125         unique_headers = list(set(all_headers))
> 126  
> 127         # Preallocate list of lists composed of NULLs.
> (Pdb) one_row
> ['Experiment: REDACTED', 'SessionDate: xx-xx-xxxx', 'SessionTime: xx:xx:xx', 'RandomSeed: 2079008169', 'Group: 1', 'Subject:123', 'Session: 1', 'runnumber: run5', 'triggersetup: scan start', 'buttonboxline: SRBox line 5', 'Display.RefreshRate: 61.779', 'trigger: 5', 'scanstart1.OnsetDelay: 3', 'scanstart1.OnsetTime: 9638', 'scanstart1.DurationError: -999999', 'scanstart1.RTTime: 56811', 'scanstart1.RT: 47173', 'scanstart1.RESP: 5', 'scanstart2.OnsetDelay: 4', 'scanstart2.OnsetTime: 56820', 'scanstart2.DurationError: -4', 'scanstart3.OnsetDelay: 0', 'scanstart3.OnsetTime: 58816', 'scanstart3.DurationError: 0', 'scanstart4.OnsetDelay: 0', 'scanstart4.OnsetTime: 60816', 'scanstart4.DurationError: 0', 'Goodbye.OnsetDelay: 0', 'Goodbye.OnsetTime: 416816', 'Goodbye.DurationError: 0', 'sscanstart1.OnsetDelay: 0', 'sscanstart1.OnsetTime: 0', 'sscanstart1.DurationError: 0', 'sscanstart1.RTTime: 0', 'sscanstart1.RT: 0', 'sscanstart1.RESP: ', 'sscanstart4.OnsetDelay: 0', 'sscanstart4.OnsetTime: 0', 'sscanstart4.DurationError: 0', 'sscanstart4.RTTime: 0', 'sscanstart4.RT: 0', 'sscanstart4.RESP: ', 'eprimestart1.OnsetDelay: 0', 'eprimestart1.OnsetTime: 0', 'eprimestart1.DurationError: 0', 'eprimestart1.RTTime: 0', 'eprimestart1.RT: 0', 'eprimestart1.RESP: ', 'eprimestart2.OnsetDelay: 0', 'eprimestart2.OnsetTime: 0', 'eprimestart2.DurationError: 0', 'eprimestart3.OnsetDelay: 0', 'eprimestart3.OnsetTime: 0', 'eprimestart3.DurationError: 0', 'eprimestart4.OnsetDelay: 0', 'eprimestart4.OnsetTime: 0', 'eprimestart4.DurationError: 0'](Pdb) 

I don't python so I'm not quite sure what it's chocking on, but if I had to guess it would be those "RESP: " headers with no associated value. Note that this was from a successful run and not an aborted one.

**Comment by tsalo** [comment]
The function is searching for the string ": " in each line from each chunk of text (corresponding to a row in the edat file). Everything before ": " is assumed to indicate the column to which the data in that line belong.
In this case, it seems to be breaking because of the line "Subject:123", which doesn't have a space after the colon. I could remove the need for a space and then strip leading whitespace when the data are pulled, but I've always assumed that the space was added automatically by E-Prime. Is there any chance the space is missing because someone edited the text file directly?

**Comment by Setsu-BHMT** [comment]
I don't think so, as I have a couple dozen files that all have this problem.

**Comment by tsalo** [comment]
I made some changes so that the space after the colon is no longer expected. Please let me know if the changes work for you.

**Comment by Setsu-BHMT** [comment]
Yep, data now correctly parses into CSVs. Great job!
