### ISSUE TITLE
How to cite `convert-eprime`

### ISSUE THREAD

**Issue by jsheunis** [tsalo/convert-eprime#8]
Hi @tsalo 

I used `convert-eprime` for a study that i'm now writing up. I would like to cite it, but I'm unsure what you'd prefer. Do you want to create a citable DOI, or should I just refer to this repo?

Thanks!

**Comment by tsalo** [comment]
I hadn't really thought about it. I can set up Zenodo and make a release at least, so you have a DOI to cite.

**Comment by tsalo** [comment]
Zenodo is now up-and-running. The DOI is `10.5281/zenodo.3831508`. Let me know if you need anything else.

I'm glad this tool was useful, and thanks for remembering to cite it!

**Comment by jsheunis** [comment]
Thank Taylor! For the DOI and the tool :)
